weights="--weights yolov5s.pt"
cfg="models/yolov5s.yaml"
cfg="models/yolov5s_oil_level.yaml"
#weights="--weights yolov5m.pt"
#cfg="models/yolov5m.yaml"
#data="data/bolt.yaml"
data="data/piezometer.yaml"
data="data/piezometer_panel_mark.yaml"
data="data/oil_level.yaml"
hyp="data/hyps/hyp.scratch.yaml"
epochs="300"
batch_size="16"
img_size="640 640"
resume=""
#resume="--resume "
#multi_scale="--multi_scale"
multi_scale=""
workers="--workers 0"
project="runs/train"
#name="piezometer_size_${img_size}_bs_${batch_size}_epoch_${epochs}"
name="oil_level"
save_period="-1"
no_auto_anchor="--noautoanchor"
no_auto_anchor=""
python train.py $weights --cfg $cfg --data $data --hyp $hyp --epochs $epochs --batch-size $batch_size --img-size $img_size $resume $multi_scale $workers --project $project --name $name --save_period $save_period $no_auto_anchor
# python train.py --weights yolov5s.pt --cfg models/yolov5s.yaml --data data/oil_level.yaml --hyp data/hyps/hyp.scratch.yaml --batch-size 16 --img-size 640 640
